### PR TITLE
Allow configuration of arbitrary key/value pairs in template

### PR DESCRIPTION
**Pull request by Poohblah**
The current template doesn't support many configuration values that are supported in `sssd.conf` by recent versions of SSSD.  This PR allows a user to set arbitrary key/value pairs in the `sssd.conf` template instead of only the keys that are currently hard-coded into the template.  The README has also been updated to reflect the changes.

Minor formatting fixes were also applied to the README.

Changes were verified against the Chefspec tests.

### CODE REVIEW

**Comment by tas50** [comment]
I had meant to kill the attribute mess that this cookbook had become.  Thanks

**Comment by Poohblah** [comment]
Thanks! we've been using these changes internally for a while now and I only just realized that I hadn't pushed back upstream.

Let me know if you are planning on pushing a new version to the Chef Supermaket soon. :)

**Comment by tas50** [comment]
I'm going to get docker based test kitchen runs in Travis going and then I'll push this up as a new major version since it moves around attributes.

**Comment by Poohblah** [comment]
Awesome, thanks again!

**Pull request merged**
